/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum BarCodeType {
  Bookland,
  CODE_39,
  CODE_128,
  EAN_8,
  EAN_13,
  Industrial_2of5,
  Interleaved_2of5,
  Standard_2of5,
  UPC_A,
  UPC_E,
  USD_3
}
