/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Mask_ComplexDouble : MaskBase {
  private HandleRef swigCPtr;

  internal Mask_ComplexDouble(IntPtr cPtr, bool cMemoryOwn) : base(VisionLabPINVOKE.Mask_ComplexDouble_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Mask_ComplexDouble obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Mask_ComplexDouble() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          VisionLabPINVOKE.delete_Mask_ComplexDouble(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Mask_ComplexDouble() : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_0(), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public Mask_ComplexDouble(Mask_ComplexDouble mask) : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_1(Mask_ComplexDouble.getCPtr(mask)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public Mask_ComplexDouble(int height, int width) : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_2(height, width), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public Mask_ComplexDouble(int height, int width, SWIGTYPE_p_std__complexT_double_t v) : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_3(height, width, SWIGTYPE_p_std__complexT_double_t.getCPtr(v)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public Mask_ComplexDouble(int height, int width, int orgX, int orgY, SWIGTYPE_p_std__complexT_double_t v) : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_4(height, width, orgX, orgY, SWIGTYPE_p_std__complexT_double_t.getCPtr(v)), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public Mask_ComplexDouble(int height, int width, int orgX, int orgY) : this(VisionLabPINVOKE.new_Mask_ComplexDouble__SWIG_5(height, width, orgX, orgY), true) {
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsEqual_Op(Mask_ComplexDouble mask) {
    bool ret = VisionLabPINVOKE.Mask_ComplexDouble_IsEqual_Op(swigCPtr, Mask_ComplexDouble.getCPtr(mask));
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Not(Mask_ComplexDouble mask) {
    bool ret = VisionLabPINVOKE.Mask_ComplexDouble_Not(swigCPtr, Mask_ComplexDouble.getCPtr(mask));
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Mask_ComplexDouble Assign_Op(Mask_ComplexDouble mask) {
    Mask_ComplexDouble ret = new Mask_ComplexDouble(VisionLabPINVOKE.Mask_ComplexDouble_Assign_Op(swigCPtr, Mask_ComplexDouble.getCPtr(mask)), false);
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMask(int height, int width, int orgX, int orgY) {
    VisionLabPINVOKE.Mask_ComplexDouble_SetMask(swigCPtr, height, width, orgX, orgY);
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__complexT_double_t GetMaskValue(int x, int y) {
    SWIGTYPE_p_std__complexT_double_t ret = new SWIGTYPE_p_std__complexT_double_t(VisionLabPINVOKE.Mask_ComplexDouble_GetMaskValue(swigCPtr, x, y), true);
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMaskValue(int x, int y, SWIGTYPE_p_std__complexT_double_t v) {
    VisionLabPINVOKE.Mask_ComplexDouble_SetMaskValue(swigCPtr, x, y, SWIGTYPE_p_std__complexT_double_t.getCPtr(v));
    if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__complexT_double_t tab {
    set {
      VisionLabPINVOKE.Mask_ComplexDouble_tab_set(swigCPtr, SWIGTYPE_p_std__complexT_double_t.getCPtr(value));
      if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      IntPtr cPtr = VisionLabPINVOKE.Mask_ComplexDouble_tab_get(swigCPtr);
      SWIGTYPE_p_std__complexT_double_t ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_std__complexT_double_t(cPtr, false);
      if (VisionLabPINVOKE.SWIGPendingException.Pending) throw VisionLabPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
