/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class SWIGTYPE_p_f_r_std__istream_r_std__ostream_r_JL_VisionLib_V3__VisLibCmdInt__void {
  private HandleRef swigCPtr;

  internal SWIGTYPE_p_f_r_std__istream_r_std__ostream_r_JL_VisionLib_V3__VisLibCmdInt__void(IntPtr cPtr, bool futureUse) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  protected SWIGTYPE_p_f_r_std__istream_r_std__ostream_r_JL_VisionLib_V3__VisLibCmdInt__void() {
    swigCPtr = new HandleRef(null, IntPtr.Zero);
  }

  internal static HandleRef getCPtr(SWIGTYPE_p_f_r_std__istream_r_std__ostream_r_JL_VisionLib_V3__VisLibCmdInt__void obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
}
