/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum CoordConversion {
  CConv_LeftTop,
  CConv_RightTop,
  CConv_LeftBotom,
  CConv_RightBotom,
  CConv_Round
}
